version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: laravel_pass
          MYSQL_DATABASE: testing_db
    steps:
      - checkout
      - run:
          name: Install PHP Dependencies
          command: |
            cd src
            sudo apt-get update
            sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip
            sudo docker-php-ext-configure gd --with-freetype --with-jpeg
            sudo docker-php-ext-install gd
            sudo docker-php-ext-install pdo pdo_mysql
            composer install
      - run:
          name: Install MySQL Client
          command: sudo apt-get install -y default-mysql-client
      - run:
          name: Set up environment
          command: |
            cd src
            cp .env.testing .env
            php artisan key:generate
      - run:
          name: Wait for MySQL to be ready
          command: sleep 10
      - run:
          name: Test MySQL Connection
          command: |
            mysql -u root -p$MYSQL_ROOT_PASSWORD -h mysql -e "SHOW DATABASES;"  # 修正：`mysql`ホストを使用
      - run:
          name: Run Database Migration
          command: |
            cd src
            php artisan migrate --env=testing --force
      - run:
          name: Run Tests
          command: |
            cd src
            vendor/bin/phpunit --coverage-text

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
