version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node  # メインのイメージ
    steps:
      # コードをチェックアウト
      - checkout

      # PHP依存パッケージと拡張モジュールのインストール
      - run:
          name: Install PHP Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip
            docker-php-ext-configure gd --with-freetype --with-jpeg
            docker-php-ext-install gd
            docker-php-ext-install pdo pdo_mysql
            composer install

      # 環境変数とアプリケーションキーの設定
      - run:
          name: Set up environment
          command: |
            cp .env.testing .env  # テスト用環境をセットアップ
            php artisan key:generate

      # Docker Composeを使ってサービスを起動
      - run:
          name: Run Docker Compose
          command: docker-compose up -d

      # MySQLの起動を待機
      - run:
          name: Wait for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 60s

      # MySQL接続テスト
      - run:
          name: Test MySQL Connection
          command: mysql -u root -proot -h 127.0.0.1 -e "SHOW DATABASES;"

      # データベースマイグレーションを実行
      - run:
          name: Run Database Migration
          command: php artisan migrate --env=testing --force

      # PHPUnitテストを実行
      - run:
          name: Run Tests
          command: vendor/bin/phpunit --coverage-text

      # SSHキーを作成してAWSにデプロイ
      - run:
          name: Deploy to AWS EC2
          command: |
            echo "$EC2_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$EC2_PUBLIC_IP 'cd /home/ec2-user/coachtech-furima/src && git pull origin main && composer install && php artisan migrate --force'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
