jobs:
  build:
    docker:
      - image: circleci/php:7.4-node
        environment:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: testing_db
          DB_USERNAME: laravel_user
          DB_PASSWORD: laravel_pass
    steps:
      - checkout
      - run:
          name: Install PHP Dependencies
          command: |
            cd src
            sudo apt-get update
            sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip
            sudo docker-php-ext-configure gd --with-freetype --with-jpeg
            sudo docker-php-ext-install gd
            composer install
      - run:
          name: Set up database
          command: |
            sudo apt-get install -y mysql-server
            sudo service mysql start
            mysql -u root -e 'CREATE DATABASE testing_db;'
      - run:
          name: Run Tests
          command: |
            cd src
            cp .env.example .env
            php artisan key:generate
            php artisan migrate --env=testing
            vendor/bin/phpunit --coverage-text
