version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node
    steps:
      - checkout
      - run:
          name: Ensure composer.json exists
          command: |
            if [ ! -f composer.json ]; then
              echo "composer.json not found. Please ensure it exists in the project root."
              exit 1
            fi
      - run:
          name: Install PHP Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip
            sudo docker-php-ext-configure gd --with-freetype --with-jpeg
            sudo docker-php-ext-install gd
            composer install
      - run:
          name: Run Tests
          command: |
            cp .env.example .env
            php artisan key:generate
            vendor/bin/phpunit --coverage-text

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
